name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - names: Checkout the repository
        uses: actions/checkout@main
      - names: Build the OS
        uses: make -C hariboslinux
      - names: Upload the OS image
        uses: actions/upload-artifact@main
	with:
	  name: FAT12 floppy disc raw image
	  path: hariboslinux/haribos.img

