name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Build the OS
        run: make
      - name: Upload the OS image
        uses: actions/upload-artifact@main
        with:
          name: FAT12 floppy disc raw image
          path: haribos.img

